- name: Verificar status do serviço Spooler
  hosts: windows
  gather_facts: no
  tasks:
    - name: Executar Get-Service para Spooler
      ansible.windows.win_shell: |
        Get-Service -Name "Spooler" | Select-Object -Property Status
      register: spooler_status

    - name: Exibir status
      debug:
        msg: "Status do serviço Spooler: {{ spooler_status.stdout_lines }}"
