---
- name: Instalar Escala Web Service
  hosts: windows
  gather_facts: no
  
  tasks:

    - name: Garantir que a pasta C:\escalasoft existe
      win_file:
        path: C:\escalasoft
        state: directory

    - name: Garantir que a pasta C:\escalasoft\ws existe
      win_file:
        path: C:\escalasoft\ws
        state: directory

    - name: Garantir que a pasta ws do cliente existe
      win_file:
        path: "C:\\escalasoft\\ws\\{{ nomeservico }}"
        state: directory

    - name: Copiar todos os arquivos de executaveis/ws para a pasta do cliente
      win_copy:
        src: "executaveis/ws/"
        dest: "C:\\escalasoft\\ws\\{{ nomeservico }}\\"
        overwrite: yes

    - name: Instalar o serviço Escala Web Service
      win_command: >
        C:\Windows\Microsoft.NET\Framework\v4.0.30319\installUtil.exe /NOMESERVICO={{ nomeservico }} /SERVIDOR={{ server }} /SISTEMA={{ sistema }} C:\escalasoft\ws\{{ nomeservico }}\EscalaWebService.exe
