- name: Finalizar processos no Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Forçar kill de processos
      ansible.windows.win_command: taskkill /F /IM {{ item }}
      ignore_errors: yes
      loop:
        - EscalaServer.exe
        - ESCALAPROCESSSYSTEM.EXE
        - Escalasoft.Tecnologia.EscalaSwarm.exe
        - Escala.exe