- name: Reiniciar serviço no Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Reiniciar o serviço "{{ servico }}"
      ansible.windows.win_service:
        name: "{{ servico }}"
        state: restarted
